-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. UNITS (e.g., "Algebra", "Geometry") or Chapters
create table units (
  id uuid default uuid_generate_v4() primary key,
  title text not null,
  grade integer not null, -- 8 or 9
  order_index integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. LESSONS
create table lessons (
  id uuid default uuid_generate_v4() primary key,
  unit_id uuid references units(id) on delete cascade,
  title text not null,
  slug text unique, -- for friendly URLs if needed
  
  -- Content
  content text, -- HTML content from TipTap
  type text check (type in ('theory', 'practice')) default 'theory',
  
  -- Metadata
  order_index integer default 0,
  is_published boolean default false,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. RLS (Row Level Security)
-- For now, we'll allow public read, but authenticated write (Admin)
alter table units enable row level security;
alter table lessons enable row level security;

-- Policy: Everyone can read
create policy "Public units are viewable by everyone" on units for select using (true);
create policy "Public lessons are viewable by everyone" on lessons for select using (true);

-- Policy: Only authenticated users can insert/update/delete (Assumes we will setup Auth later)
-- For development simplicity, we will allow ALL operations for the user for now
create policy "Enable all for authenticated users" on units for all using (auth.role() = 'authenticated');
create policy "Enable all for authenticated users" on lessons for all using (auth.role() = 'authenticated');

-- ==========================================
-- USER PROVIDED: KNOWLEDGE GRAPH SCHEMA
-- ==========================================

-- 1. Bảng lưu trữ các Concept (Đơn vị kiến thức)
create table math_concepts (
  id text primary key, -- Ví dụ: MATH6_V1_C1_SET
  grade int not null,
  name text not null,
  definition text,
  vol int,
  chapter int,
  page_start int,
  tags text[], -- Array các tag ví dụ ['đại số', 'hình học']
  embedding vector(1536), -- (Tuỳ chọn) Nếu bạn dùng OpenAI Embedding để search semantic
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Bảng lưu trữ mối quan hệ (Knowledge Graph)
-- Bảng này cực quan trọng để AI "truy vết" (trace back) lỗi sai của học sinh
create table concept_relationships (
  id bigint generated by default as identity primary key,
  source_id text references math_concepts(id) on delete cascade, -- Kiến thức hiện tại (vd: Lớp 7)
  target_id text references math_concepts(id) on delete cascade, -- Kiến thức cần thiết (vd: Lớp 6)
  relationship_type text check (relationship_type in ('requires', 'related_to', 'part_of')),
  description text -- Giải thích tại sao cần (vd: "Cần biết quy đồng mẫu số để cộng số hữu tỉ")
);

-- 3. Indexes để truy vấn nhanh
create index idx_concepts_grade on math_concepts(grade);
create index idx_relationships_source on concept_relationships(source_id);
create index idx_relationships_target on concept_relationships(target_id);

-- Enable RLS for these new tables too
alter table math_concepts enable row level security;
alter table concept_relationships enable row level security;

create policy "Public concepts view" on math_concepts for select using (true);
create policy "Public relationships view" on concept_relationships for select using (true);
create policy "Admin concepts edit" on math_concepts for all using (auth.role() = 'authenticated');
create policy "Admin relationships edit" on concept_relationships for all using (auth.role() = 'authenticated');
